### ISSUE TITLE
采集使用IP代理时panic

### ISSUE THREAD

**Issue by vckai** [vckai/novel#26]
我在测试过程中项目直接崩溃了！

panic: runtime error: slice bounds out of range [2:1]

goroutine 23 [running]:
github.com/vckai/novel/app/services.(*Proxy).Del(0xc00018a4c0, 0xc0001f2400, 0xe, 0x0, 0xc000416ae0)
        /home/ping/go/src/github.com/vckai/novel/app/services/proxy.go:153 +0x253
github.com/vckai/novel/app/services.(*Proxy).check(0xc00018a4c0)
        /home/ping/go/src/github.com/vckai/novel/app/services/proxy.go:201 +0x2e4
github.com/vckai/novel/app/services.(*Proxy).Init.func2(0xc00018a4c0)
        /home/ping/go/src/github.com/vckai/novel/app/services/proxy.go:76 +0x91
created by github.com/vckai/novel/app/services.(*Proxy).Init
        /home/ping/go/src/github.com/vckai/novel/app/services/proxy.go:70 +0x61

_Originally posted by @344085057 in https://github.com/vckai/novel/issues/25#issuecomment-591485868_

**Comment by vckai** [comment]
@344085057 看着像是没有加锁导致的，我跟进下这个问题。

可以考虑使用之前版本的[proxy.go](https://github.com/vckai/novel/blob/d8de161eda1b27425c7f3630e86c615f5a18ba4b/app/services/proxy.go)先进行采集。在`conf/app.conf`文件中增加两个配置项，参考[app.conf](https://github.com/vckai/novel/blob/d8de161eda1b27425c7f3630e86c615f5a18ba4b/conf/app.conf.example)。

**Comment by pingProMax** [comment]
好的 -_-

**Comment by vckai** [comment]
增加了锁来解决该panic问题，我手头没有可用的代理IP列表，麻烦帮忙测试看下~

**Comment by pingProMax** [comment]
好的  有时间我会测试下

**Comment by pingProMax** [comment]
昨天在服务器跑了一晚上  似乎没有问题了

**Comment by vckai** [comment]
好的~有问题随时反馈~

**Comment by pingProMax** [comment]
代理采集似乎还有问题 开启后没有采集了
我给你ip代理api
http://139.199.11.169:8828/api?code=qq344085057

**Comment by vckai** [comment]
已修复，请知悉：）

**Comment by pingProMax** [comment]
好的 我测试下

**Comment by pingProMax** [comment]
可以啦可以啦～～～～

**Comment by vckai** [comment]
好的，感谢反馈~

**Comment by pingProMax** [comment]
似乎还有问题，今天程序在服务器上崩溃了，开启了代理采集。。
因为在windows服务器跑的 日志没找到。。

**Comment by vckai** [comment]
确实是还会出现panic

**Comment by pingProMax** [comment]
:(

**Comment by vckai** [comment]
最近有点忙，主要是这个不太好复现，等忙过这段时间我再专门来找下这个问题吧。建议先使用旧版本的proxy.go进行采集把

**Comment by BeanWei** [comment]
这个是不是可以考虑下利用 channel 采用生产者和消费者模型去 存ip / 检查ip有效性。
